### ISSUE TITLE
documaentation without doc app

### ISSUE THREAD

**Issue by jurajsimbs** [BohemiaInteractive/bi-service-doc#1]
Would it be possible to export documentation to static html/js files instead of running the whole thing as a node app? On dev/preprod we'd spare a lot of memory and a few ports. Or is there any reason (except that some additional work is needed to implement export to static html files) to keep it as a separate doc app?

**Comment by fogine** [comment]
Nowadays possible with `redoc-cli` package since `v2.0.0` release of `bi-service-doc`
