### ISSUE TITLE
only secure schema

### ISSUE THREAD

**Issue by jurajsimbs** [BohemiaInteractive/bi-service-doc#6]
In generated json:  
![selection_305](https://user-images.githubusercontent.com/18613927/38129072-b4d9f268-33fd-11e8-83e6-6f2089970005.png)

how can I allow only https schema? (we do not allow http on any of our envs)

**Comment by fogine** [comment]
no longer an issue with in the `2.0.0` release... which uses OpenAPI v3..
In the new version, the protocol is taken from `baseUrl` of `bi-service` config.
